# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "filesorter"
version = "0.1.0"
authors = ["ElXreno <elxreno@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
directories = "2.0.2"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"