[package]
name = "file-sorter"
version = "0.1.0"
authors = ["ElXreno <elxreno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#config = "0.9.3"
#directories = "2.0.2"
#ron = "0.5.1"
#log = "0.4.8"
tree_magic = "0.2.1"