[package]
name = "filesorter"
version = "0.2.0"
authors = ["ElXreno <elxreno@gmail.com>"]
repository = "https://github.com/ElXreno/filesorter"
readme = "README.md"
license = "GPL-3.0"
keywords = [
    "file",
    "sort"
]
categories = ["command-line-utilities"]
description = """
Utility for sorting files in directory writen in Rust
"""
edition = "2018"


# Profiles
[profile.dev]
opt-level = 0
panic = "abort"

[profile.release]
debug = false
codegen-units = 1
lto = true


[dependencies]
directories = "2.0.2"
serde = "1.0.105"
serde_derive = "1.0.104"
serde_json = "1.0.48"
clap = "2.33.0"
chrono = "0.4.11"
