# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "filesorter"
version = "0.1.1"
authors = ["ElXreno <elxreno@gmail.com>"]
edition = "2018"


# Profiles
[profile.dev]
opt-level = 2
panic = "abort"

[profile.release]
debug = false
codegen-units = 1
lto = true


[dependencies]
directories = "2.0.2"
serde = "1.0.103"
serde_derive = "1.0.104"
serde_json = "1.0.44"
clap = "2.33.0"
